version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: AlumnoNFL
      MYSQL_DATABASE: rls
      MYSQL_USER: auditoriasrsl
      MYSQL_PASSWORD: yHTT5LFuuUnYiW8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - webnet

  php:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./codigo:/var/www/html
    networks:
      - webnet

  web:
    image: nginx:latest
    #restart: always
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - ./codigo:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     # - ./codigo/style:/usr/share/nginx/style  # Se añadió este volumen para la carpeta de CSS
    networks:
      - webnet
    depends_on:
      - php
      - db

volumes:
  mysql_data:

networks:
  webnet:
